server:
  port: 8700
spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      #      exclude: WEB-INF/**
      log-condition-evaluation-delta: false
#      网关是客户端与后端服务之间的唯一出入口，请求从客户端到后端服务要经过网关，响应从后端服务返回客户端同样要经过网关。
  cloud:
    gateway:
      #          配置跨域请求处理
#      globalcors:
#        corsConfigurations:
#          '[/**]':  #网关所有路径上都有效
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders: "*"
##            允许携带凭证，不能和 allowedOrigins: "*"一起使用必须指定具体的源
#            allowCredentials: true

      routes:
        - id: gateway
          predicates:
#            - Path=/user/{segment}
            - Path=/user/**

#            - After=2025-06-30T12:00:00Z[Asia/Shanghai]
#            - Between=2025-06-30T00:00:00Z[Asia/Shanghai],2025-10-30T12:00:00Z[Asia/Shanghai]
#            - Cookie=uid,1234567
#            - Header=openId,\d+
#            - Method=GET
#            - Query=username

#            - RemoteAddr=192.168.3.0/23

          uri: lb://service-user

          filters:
#            自定义局部过滤器
            - AddAppCheckAuth=token1,123456
##            添加前缀
#            - PrefixPath=/user
##            去除前缀第一个路径
#            - StripPrefix=1
##            添加响应头
#            - AddResponseHeader=hello,world
##            添加请求参数
#            - AddRequestParameter=uid,111111





#        - id: gatwayOrder
#          predicates:
#            - Path=/user/orders
#          uri: http://localhost:8002
#    nacos:
#      discovery:
#        server-addr:  http://192.168.10.1:8848

logging:
  level:
    # 核心：开启网关路由匹配相关的DEBUG日志
    org.springframework.cloud.gateway: DEBUG
    # 可选：开启HTTP请求转发的详细日志（包括转发地址、响应等）
    reactor.netty.http.client: DEBUG
    # 可选：开启服务发现相关日志（如果用了nacos/eureka）
    org.springframework.cloud.client.discovery: DEBUG